-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 21:59:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `public` DEFAULT CHARACTER SET utf8 ;
USE `public` ;

-- -----------------------------------------------------
-- Table `public`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`cidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_estado_idx` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `id_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `public`.`estados` (`id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`bairros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`bairros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_cidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_cidade_idx` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `id_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `public`.`cidades` (`id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `numero` INT NOT NULL,
  `id_bairro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_bairro_idx` (`id_bairro` ASC) VISIBLE,
  CONSTRAINT `id_bairro`
    FOREIGN KEY (`id_bairro`)
    REFERENCES `public`.`bairros` (`id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `celular` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `id_endereco` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `id_endereco_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `id_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `public`.`enderecos` (`id`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`turmas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nivel` ENUM('Iniciante', 'Intermediário', 'Avançado') NOT NULL,
  `periodo` ENUM('Matutino', 'Vespertino', 'Noturno') NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`matriculas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `id_turma` INT NOT NULL,
  `data_matricula` DATE NOT NULL,
  `data_encerramento` DATE NULL,
  `dia_vencimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_alunos_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `id_turma_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `public`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_turma`
    FOREIGN KEY (`id_turma`)
    REFERENCES `public`.`turmas` (`id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`faturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public`.`faturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_matricula` INT NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `data_pagamento` DATE NULL,
  `data_cancelamento` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `id_matricula_idx` (`id_matricula` ASC) VISIBLE,
  CONSTRAINT `id_matricula`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `public`.`matriculas` (`id`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;